# Generated by Django 5.0.2 on 2024-03-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
