# Generated by Django 5.0.2 on 2024-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPages', '0003_visitor1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthenticate',
            name='First',
            field=models.BooleanField(default=False),
        ),
    ]
