# Generated by Django 5.0.2 on 2024-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPages', '0004_userauthenticate_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthenticate',
            name='subscription_id2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
